name: Xianshen He's information
url: https://xianshenhe.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module


# The path structure for blog posts.

# Sections on the "people" page.




# Number of news stories on the front page.
#front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
#collections:
  #projects:
    #output: true

# Navigation bar links.
navigation:
  - title: 个人信息  Personal Information
    link: /
  - title: 交流平台 Communication Platform
    link: /research.html
  - title: 更多 More
    link: /publications.html
