name: 蔡嘉琪的网站  CAI Jiaqi's website
url: https://jiaqicai22.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 教师 Faculty
  - key: grad
    name: 研究生 Graduate Students



# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: CJQ Home
    link: /
  - title: 课程项目 project
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
